backend:
  build:
    dockerfile: api/src/main/docker/Dockerfile
  image: 'gesap-interno/backend'
  container_name: 'gesap-interno-backend'
  environment:
    BE_PORT: ${BE_PORT}
  ports:
    - 60196:9090
  restart: always
  network_mode: bridge



